### ISSUE TITLE
R-T3.4-15: The IaC miner should support Gitlab

### ISSUE THREAD

**Issue by dardin88** [stefanodallapalma/iac-miner#6]
ID | R-T3.4-15
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer/QoS Engineer/Release Manager, I want to crawl also software repositories in Gitlab.
Requirement | The IaC miner should allow developers to crawl software repositories in Gitlab.
Priority | Should have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study

**Comment by dardin88** [comment]
@gcasale

**Comment by gcasale** [comment]
Approved
