### ISSUE TITLE
R-T3.4-16: The IaC miner should support JIRA

### ISSUE THREAD

**Issue by dardin88** [stefanodallapalma/iac-miner#7]
ID | R-T3.4-16
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer/QoS Engineer/Release Manager, I want to crawl also issues stored in JIRA.
Requirement | The IaC miner should support JIRA as an issue tracker to crawl issues.
Priority | Should have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study

**Comment by dardin88** [comment]
@gcasale

**Comment by gcasale** [comment]
Approved
